---
- hosts: 172.31.35.71
  become: yes
  tasks:
  - name: i want to direct linux command
    command: apt-get install git
    register: myresult

  - name: i want to disply my first task result
    debug:
       msg: "myresult: {{myresult}}"
       
  - name: install git
    apt:
      name: git
      state: present
    when: myresult.stderr !=""

  - name: install tree
    apt:  
       name: tree
       state: present
    when: myresult.stderr ==""
      
